# docker-compose requires the x- prefix for unrelated YAML nodes
x-zeek-template: &ZEEK_BASE
  image: zeektest:latest
  ulimits:
    nofile: 1024

x-zeek-controller: &ZEEK_CONTROLLER
  command: /usr/local/zeek/bin/zeek -j site/testing/controller.zeek
  environment:
    - DEBIAN_FRONTEND=noninteractive
    - DEBCONF_NOWARNINGS=yes
    - ZEEK_DEFAULT_LISTEN_ADDRESS=0.0.0.0
    - ZEEK_MANAGEMENT_SPOOL_DIR
    - ZEEK_MANAGEMENT_STATE_DIR
    - ZEEK_MANAGEMENT_TESTING
  expose:
    - "2149"
    - "2150"
  volumes:
    - ./zeekscripts:/usr/local/zeek/share/zeek/site/testing:z
    - ./scripts:/usr/local/bin:z

x-zeek-agent: &ZEEK_AGENT
  command: /usr/local/zeek/bin/zeek -j site/testing/agent.zeek
  environment:
    - DEBIAN_FRONTEND=noninteractive
    - DEBCONF_NOWARNINGS=yes
    - ZEEK_DEFAULT_LISTEN_ADDRESS=0.0.0.0
    - ZEEK_MANAGEMENT_SPOOL_DIR
    - ZEEK_MANAGEMENT_STATE_DIR
    - ZEEK_MANAGEMENT_TESTING
  expose:
    - "2151"
    - "9090-9999"
  volumes:
    - ./zeekscripts:/usr/local/zeek/share/zeek/site/testing:z
    - ./scripts:/usr/local/bin:z

x-zeek-client: &ZEEK_CLIENT
  tty: true
  volumes:
    - ./scripts:/usr/local/bin:z
    - ./etc:/usr/local/etc:z
  environment:
    - DEBIAN_FRONTEND=noninteractive
    - DEBCONF_NOWARNINGS=yes

services:
  controller:
    hostname: controller
    <<: [*ZEEK_BASE, *ZEEK_CONTROLLER]

  inst1:
    hostname: inst1
    <<: [*ZEEK_BASE, *ZEEK_AGENT]

  inst2:
    hostname: inst2
    <<: [*ZEEK_BASE, *ZEEK_AGENT]

  client:
    hostname: client
    <<: [*ZEEK_BASE, *ZEEK_CLIENT]
