version: "3"

# docker-compose requires the x- prefix for unrelated YAML nodes
x-zeek-template: &ZEEK_BASE
  image: zeektest:latest
  ulimits:
    nofile: 1024

x-zeek-controller: &ZEEK_CONTROLLER
  command: /usr/local/zeek/bin/zeek -j "site/testing/${ZEEK_ENTRYPOINT:-controller-and-agent.zeek}"
  environment:
    - ZEEK_DEFAULT_LISTEN_ADDRESS=0.0.0.0
    - ZEEK_MANAGEMENT_SPOOL_DIR
    - ZEEK_MANAGEMENT_STATE_DIR
    - ZEEK_MANAGEMENT_TESTING
  expose:
    - "2149"
    - "2150"
    - "9090-9999"
  hostname: controller
  volumes:
    - ./zeekscripts:/usr/local/zeek/share/zeek/site/testing:z
    - ./scripts:/usr/local/bin:z
    - ./etc:/usr/local/etc:z

x-zeek-client: &ZEEK_CLIENT
  hostname: client
  tty: true
  volumes:
    - ./scripts:/usr/local/bin:z
    - ./etc:/usr/local/etc:z

services:
  controller:
    <<: [*ZEEK_BASE, *ZEEK_CONTROLLER]

  client:
    <<: [*ZEEK_BASE, *ZEEK_CLIENT]
