#! /usr/bin/env bash

testname=$(echo "$1" | sed 's/[^a-zA-Z0-9]/_/g')

# Preserve the controller's persistent state:
controller=${testname}__controller_1
if docker ps -a | grep -q $controller; then
    mkdir -p controller/var
    docker cp $controller:/usr/local/zeek/var/lib controller/var/lib
    docker cp $controller:/usr/local/zeek/spool controller/spool
    docker cp $controller:/usr/local/zeek/logs controller/logs
fi

# Grab the Docker logs
docker-compose -p ${testname}_ -f docker-compose.yml logs >docker-compose.logs

[ -n "$TEST_SKIP_DOCKER_TEARDOWN" ] && exit 0
[ "$TEST_FAILED" -eq 1 ] && [ -n "$TEST_SKIP_DOCKER_TEARDOWN_ON_FAILURE" ] && exit 0

if [ -z "$testname" ]; then
    echo "WARNING: btest teardown got no test name"
    exit 0
fi

if [ ! -f docker-compose.yml ]; then
    echo "WARNING: btest teardown found no docker-compose.yml"
    exit 0
fi

# Don't wait at all for clean container shutdown
docker-compose -p ${testname}_ -f docker-compose.yml down -t 0

exit 0
